<?php

namespace TranslationsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanguagePairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguagePairRepository extends EntityRepository
{
}
